//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 04:07:52 PM ICT 
//


package com.qph.restdemo.service.report.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.qph.restdemo.service.report.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.qph.restdemo.service.report.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link SiteDetails }
     * 
     */
    public SiteDetails createSiteDetails() {
        return new SiteDetails();
    }

    /**
     * Create an instance of {@link WorkerNumber }
     * 
     */
    public WorkerNumber createWorkerNumber() {
        return new WorkerNumber();
    }

    /**
     * Create an instance of {@link SaqResultsList }
     * 
     */
    public SaqResultsList createSaqResultsList() {
        return new SaqResultsList();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link SaqResult }
     * 
     */
    public SaqResult createSaqResult() {
        return new SaqResult();
    }

    /**
     * Create an instance of {@link CompanySite }
     * 
     */
    public CompanySite createCompanySite() {
        return new CompanySite();
    }

}
