//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 11:44:26 PM ICT 
//


package com.qph.restdemo.service.report.dto;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentFont" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exportedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saqResultsTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteDetails" type="{}SiteDetails"/>
 *         &lt;element name="workerNumberList" type="{}WorkerNumberList"/>
 *         &lt;element name="saqResultsList" type="{}SaqResultsList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contentFont",
    "by",
    "exportedDate",
    "saqResultsTitle",
    "siteDetails",
    "workerNumberList",
    "saqResultsList"
})
@XmlRootElement(name = "Report")
public class Report {

    @XmlElement(required = true)
    protected String contentFont;
    @XmlElement(required = true)
    protected String by;
    @XmlElement(required = true)
    protected String exportedDate;
    @XmlElement(required = true)
    protected String saqResultsTitle;
    @XmlElement(required = true)
    protected SiteDetails siteDetails;
    @XmlElement(required = true)
    protected WorkerNumberList workerNumberList;
    @XmlElement(required = true)
    protected List<SaqResultsList> saqResultsList;

    /**
     * Gets the value of the contentFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentFont() {
        return contentFont;
    }

    /**
     * Sets the value of the contentFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentFont(String value) {
        this.contentFont = value;
    }

    /**
     * Gets the value of the by property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBy() {
        return by;
    }

    /**
     * Sets the value of the by property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBy(String value) {
        this.by = value;
    }

    /**
     * Gets the value of the exportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportedDate() {
        return exportedDate;
    }

    /**
     * Sets the value of the exportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportedDate(String value) {
        this.exportedDate = value;
    }

    /**
     * Gets the value of the saqResultsTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaqResultsTitle() {
        return saqResultsTitle;
    }

    /**
     * Sets the value of the saqResultsTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaqResultsTitle(String value) {
        this.saqResultsTitle = value;
    }

    /**
     * Gets the value of the siteDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SiteDetails }
     *     
     */
    public SiteDetails getSiteDetails() {
        return siteDetails;
    }

    /**
     * Sets the value of the siteDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteDetails }
     *     
     */
    public void setSiteDetails(SiteDetails value) {
        this.siteDetails = value;
    }

    /**
     * Gets the value of the workerNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerNumberList }
     *     
     */
    public WorkerNumberList getWorkerNumberList() {
        return workerNumberList;
    }

    /**
     * Sets the value of the workerNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerNumberList }
     *     
     */
    public void setWorkerNumberList(WorkerNumberList value) {
        this.workerNumberList = value;
    }

    /**
     * Gets the value of the saqResultsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saqResultsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaqResultsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SaqResultsList }
     * 
     * 
     */
    public List<SaqResultsList> getSaqResultsList() {
        if (saqResultsList == null) {
            saqResultsList = new ArrayList<SaqResultsList>();
        }
        return this.saqResultsList;
    }

}
