//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.22 at 04:07:52 PM ICT 
//


package com.qph.restdemo.service.report.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkerNumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkerNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workderType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="women" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="men" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkerNumber", propOrder = {
    "workderType",
    "women",
    "men",
    "total"
})
public class WorkerNumber {

    @XmlElement(required = true)
    protected String workderType;
    protected int women;
    protected int men;
    protected int total;

    /**
     * Gets the value of the workderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkderType() {
        return workderType;
    }

    /**
     * Sets the value of the workderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkderType(String value) {
        this.workderType = value;
    }

    /**
     * Gets the value of the women property.
     * 
     */
    public int getWomen() {
        return women;
    }

    /**
     * Sets the value of the women property.
     * 
     */
    public void setWomen(int value) {
        this.women = value;
    }

    /**
     * Gets the value of the men property.
     * 
     */
    public int getMen() {
        return men;
    }

    /**
     * Sets the value of the men property.
     * 
     */
    public void setMen(int value) {
        this.men = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

}
